### ISSUE TITLE
Twitter new API

### ISSUE THREAD

**Issue by joomleb** [akeeba/sociallogin#100]
Hi @nikosdion 
as you announced on February 2nd the  [Twitter Login feature has been discontinued](https://github.com/akeeba/sociallogin/wiki/Twitter).
It dues to the [Twitter announcement](https://twitter.com/TwitterDev/status/1621026986784337922) that from February 9th the free API access would been cutted off.
Now, as far as I know, after a little bit of confusion (as always), [Twitter has restored it](https://twitter.com/TwitterDev/status/1641222782594990080) with new API release and the "Login with Twitter" feature [should be included now](https://developer.twitter.com/en) in the new free API.

Am I missing anything ? Do you agree ?
If so, would be so useful to restore the Twitter integration...

Thank you for your attention

**Comment by nikosdion** [comment]
I don't know, I don't care, and it is completely irrelevant to my decision not to support Twitter now and in the future. 

Twitter's policies change without warning or even announcement. This makes it a poor choice for integrating in any product. 

Further to that, Twitter's ownership is sympathetic to the ultra-right and the outright nazis. This is diametrically opposed to what I stand for.

As a result, my decision to remove Twitter support and never revisit it is final.
