### ISSUE TITLE
LinkedIn removed Login with LInkedIn, requires using OpenID Connect instead

### ISSUE THREAD

**Issue by peterader** [akeeba/sociallogin#106]
Hi, first of all thank you for this amazing extension and even making it free of charge. (I'm a Joomla Deluxe subscriber for many years so I'm happy to pay for excellent software but a free beer tastes always better :D) 

The issue: It appears the LinkedIn integration it no longer working. I followed the setup documentation to create the App but there is no Product "Sign In with LinkedIn". I think it has been replaced by "Sign In with LinkedIn using OpenID Connect". When trying to sign in on my website I get the following error:  HTTP 401: {"serviceErrorCode":65604,"message":"Empty oauth2 access token","status":401}

![image](https://github.com/akeeba/sociallogin/assets/1409554/41ff334c-82b0-497b-baff-67933670fa83)

Upon clicking sign in button this error appears:
![image](https://github.com/akeeba/sociallogin/assets/1409554/44b9b4bc-891b-4b1b-9e28-487a2638d1e2)

After redirecting back to my site it shows the HTTP 401 error I mentioned above.

Let me know if I can be of any help or provide further information!

#### Mandatory information

* **Joomla! version**: 3.10.12
* **PHP version**: 7.3.5
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**: Windows 10
* **Browser**: Firefox
* **Browser version**: 118.0.2 (64-bit)

**Comment by nikosdion** [comment]
OpenID Connect is completely different and incompatible. It would have been nice if one of the gazillion annoying emails LinkedIn sends would have mentioned that the old Login with LinkedIn is going away on August 1st, 2023 — but no, they think that the ramblings of Billy Bob Joe who I don't even know let alone follow on which thingamajig is better for a business sector I have never been involved with and have zero interest in is far more important to ~bust my balls~ notify me about. Typical Microsoft.

So, it looks like we need a new connector. There are good new and bad news.

The good news is that I've already done the work to create a generic OpenID Connect connector for SocialLogin, which means I'm not starting from scratch.

The bad news is that Joomla 5 will be releasing in two hours' time. Therefore, RIP my free time, for the foreseeable, ergo not a chance I will be doing that anytime soon.

**Comment by peterader** [comment]
Thanks for replying so quickly and for that little rant :) Hitchhikers guide to the galaxy comes to mind. Probably that information has been published in the planning office on Alpha Centauri. Your fault you didn't check there 🤣 

It's not a critical feature, more a nice-to-have, so I'm happy to wait and hope for the best. :)

**Comment by nikosdion** [comment]
OK, I double checked the LinkedIn documentation and they really _have not_ removed the OAuth2 integration. In fact, they just added OpenID Connect as an _alternative_ to the third and last step of the OAuth2 integration, but they explicitly state that you can use either.

I also followed the documentation instructions and they still work, albeit it takes a while until you see the OAuth 2.0 scopes. So, yeah, there's no need to change anything here.

**Comment by tomazf8** [comment]
plug in set up is not working. only openid. haw can i set up plugin? there is no r_liteprofile and r_emailaddress parameters in hte scope-

please help.

**Comment by nikosdion** [comment]
@tomazf8 https://github.com/akeeba/sociallogin/wiki/LinkedIn#setup-on-linkedin

**Comment by tomazf8** [comment]
> @tomazf8 https://github.com/akeeba/sociallogin/wiki/LinkedIn#setup-on-linkedin

i'm sorry, but after following guidelines after two weeks i dont se the required fileds in myapps. no r_liteprofile or r_emailaddres. just "openid
Use your name and photo
profile
Use your name and photo
email
Use the primary email address associated with your LinkedIn account"

**Comment by nikosdion** [comment]
Have you tried using profile and email?

**Comment by tomazf8** [comment]
I do not now where and how.

You mean instead clientid and secret?

**Comment by nikosdion** [comment]
Well, surprising absolutely nobody, LinkedIn did three nonsensical things:

1. They have not updated their OAuth 2.0 login documentation, still mentioning what is apparently the “old” way of doing it.
2. If you had created a LinkedIn app in the past the “old” way still works.
3. They have not communicated this change, or the fact their documentation is useless, anywhere.

So, yeah. You are right. You can't use SocialLogin as it is with LinkedIn and I was not able to see that because LinkedIn allowed me to use the old way with my app just fine. Typical Microsoft things (they've bought LinkedIn ages ago).

The good news is that tomorrow I will be able to publish a new version of SocialLogin which addresses this issue.

**Comment by tomazf8** [comment]
Thank you

**Comment by nikosdion** [comment]
The new release is out.

I also updated the wiki page so it more accurately represents the steps you need to follow.

For what it's worth, until at least early November the old login with OAuth 2 was still available. Apparently, not for everyone (I could see it, other people said they could not). Don't you love it when a third party provider plays this kind of tricks? Sigh.
