### ISSUE TITLE
Google: unwanted query string part after redirected back to the site, results with "Forbidden"

### ISSUE THREAD

**Issue by jaanusnurmoja** [akeeba/sociallogin#112]
When I authenticate using google plugin, the authentication itself is succesful but a blank screen with a message "Forbidden" is displayed then. 

The url looks like

https://my.site.ee/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw&code=here-is-some-code-from-google&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=none

When I remove all stuff after the code and then browse the rest of the url (https://my.site.ee/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw&code=here-is-some-code-from-google) then my site opens normally again and I am logged in with my Google credentials. 

Using Joomla 5. php 8.2

![image](https://github.com/akeeba/sociallogin/assets/1138055/f48800aa-3801-45a9-b39f-834303ddaace)
![image](https://github.com/akeeba/sociallogin/assets/1138055/6d13fb2c-9323-44cf-9c5b-16dd3b55f17c)
![image](https://github.com/akeeba/sociallogin/assets/1138055/a35025f1-0ee8-427e-8928-2c3480d0ca5e)
![image](https://github.com/akeeba/sociallogin/assets/1138055/a682366c-5047-4fe2-9d8a-1baa52609faf)
![image](https://github.com/akeeba/sociallogin/assets/1138055/5f6fdbb0-a948-4127-b3f3-3eab5a9e0edc)

**Comment by nikosdion** [comment]
Ask your host for help on this. It is either something in your `.htaccess` file, or something in the server's configuration (more specifically, one of the Atomic rules for `mod_security2` they have applied on the server) which is blocking the return URL.

The reason this URL is blocked is that Google OAuth2 scopes are in URL format. See this: `scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email`. Embedding URL-encoded URLs as URL parameters (try saying that three times fast) is a bad practice, yes, I agree. I do know that a lot of standard security configurations for hosts block it. However, Google gives you no other choice. That is how they chose to do things, that's what we get. Hence the need to talk to your host about it.

**Comment by jaanusnurmoja** [comment]
> Ask your host for help on this. It is either something in your `.htaccess` file, or something in the server's configuration (more specifically, one of the Atomic rules for `mod_security2` they have applied on the server) which is blocking the return URL.

Hm, could it be solved within php.ini ? If so, a good hint would be welcome

**Comment by nikosdion** [comment]
I already told you, you need to ask your host. If another solution existed I'd have told you.

And to make it clear: no, this has nothing to do with php.ini _as I already explained in detail above_.
