### ISSUE TITLE
Unable to make work the sign with apple option

### ISSUE THREAD

**Issue by GaetanLabrecque** [akeeba/sociallogin#115]
Hello

I just finished configuring the sign in with apple option.  I double checked everything and solved every problems I had.  The last one being that when we copy paste the certificate content we have to include everything including the begin and end private key.

Now, I am able to open a session, I enter the name, password, 2fa and then I get redirected to my joomla web site with this error.

Class "phpseclib\Crypt\RSA" not found0/home/xxx/domains/xxx.com/public_html/plugins/system/sociallogin/vendor/codercat/jwk-to-pem/src/JWKConverter.php71Array

What could be wrong?

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 5.0.3
* **PHP version**: Don't Know
* **Am I using HTTPS**: Yes
* **Server Operating System**: Don't Know
* **My device's Operating System**: Windows.
* **My device's Operating System version**: 11
* **Browser**: Chrome
* **Browser version**: 123.0.6312.58

Thank you very much for your help

**Comment by nikosdion** [comment]
Please use the following dev release https://www.akeeba.com/download/sociallogin-dev/4-8-0-dev202403251631-rev8feb9ff.html

**Comment by GaetanLabrecque** [comment]
Hello Nicholas,

We still have the same issue but the error message did change

Class "Akeeba\Plugin\Sociallogin\Apple\Extension\DateInterval" not found0/home/xxx/domains/xxx.com/public_html/plugins/sociallogin/apple/src/Extension/Plugin.php195Array

Thank you

Gaetan Labrecque
________________________________
De : Nicholas K. Dionysopoulos ***@***.***>
Envoyé : 25 mars 2024 12h33
À : akeeba/sociallogin ***@***.***>
Cc : Gaetan Labrecque ***@***.***>; Author ***@***.***>
Objet : Re: [akeeba/sociallogin] Unable to make work the sign with apple option (Issue #115)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Closed #115<https://github.com/akeeba/sociallogin/issues/115> as completed.

**Comment by nikosdion** [comment]
Please try this https://www.akeeba.com/download/sociallogin-dev/4-8-0-dev202403251734-revd530807.html

**Comment by GaetanLabrecque** [comment]
Hello Nicholas,

We are going farther.  We get back to our site but we do receive

You do not have an account on this site that corresponds to this Apple ID.

Even if I did configure the plugin to create the account
[cid:41587c77-efed-4004-a0c4-1f64529e15fa]

Thank you for your help

Gaetan Labrecque
________________________________
De : Nicholas K. Dionysopoulos ***@***.***>
Envoyé : 25 mars 2024 13h35
À : akeeba/sociallogin ***@***.***>
Cc : Gaetan Labrecque ***@***.***>; Author ***@***.***>
Objet : Re: [akeeba/sociallogin] Unable to make work the sign with apple option (Issue #115)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Please try this https://www.akeeba.com/download/sociallogin-dev/4-8-0-dev202403251734-revd530807.html

**Comment by GaetanLabrecque** [comment]
Hello Nicholas,

Did you receive this update?

What could be wrong?

it works with Google and Microsoft.  It seems like only with Apple it does not create the account in Joomla

Greetings

Gaetan Labrecque
________________________________
De : Gaetan Labrecque ***@***.***>
Envoyé : 25 mars 2024 13h52
À : akeeba/sociallogin ***@***.***>; akeeba/sociallogin ***@***.***>
Cc : Author ***@***.***>
Objet : Re: [akeeba/sociallogin] Unable to make work the sign with apple option (Issue #115)

Hello Nicholas,

We are going farther.  We get back to our site but we do receive

You do not have an account on this site that corresponds to this Apple ID.

Even if I did configure the plugin to create the account
[cid:41587c77-efed-4004-a0c4-1f64529e15fa]

Thank you for your help

Gaetan Labrecque
________________________________
De : Nicholas K. Dionysopoulos ***@***.***>
Envoyé : 25 mars 2024 13h35
À : akeeba/sociallogin ***@***.***>
Cc : Gaetan Labrecque ***@***.***>; Author ***@***.***>
Objet : Re: [akeeba/sociallogin] Unable to make work the sign with apple option (Issue #115)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Please try this https://www.akeeba.com/download/sociallogin-dev/4-8-0-dev202403251734-revd530807.html

**Comment by nikosdion** [comment]
I have read your reply, but I also have other things to do -- things which pay the bills, therefore have higher priority :) I will get back to that, but probably not for a couple of days.

**Comment by GaetanLabrecque** [comment]
No problem Nicholas

I understand. Same here, this project is not my day job.

I just wanted to be sure you did received it.

Greetings

Gaetan Labrecque
________________________________
De : Nicholas K. Dionysopoulos ***@***.***>
Envoyé : mercredi, mars 27, 2024 3:12 a.m.
À : akeeba/sociallogin ***@***.***>
Cc : Gaetan Labrecque ***@***.***>; Author ***@***.***>
Objet : Re: [akeeba/sociallogin] Unable to make work the sign with apple option (Issue #115)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

I have read your reply, but I also have other things to do -- things which pay the bills, therefore have higher priority :) I will get back to that, but probably not for a couple of days.

**Comment by GaetanLabrecque** [comment]
Hello Nicholas

I still have the same issue.  I still have "invalid request" when I come back to the site after authentification including MFA from Apple.

Microsoft and Google authentification works.

Gaetan

**Comment by nikosdion** [comment]
> You do not have an account on this site that corresponds to this Apple ID.

This means that the login worked fine, but you have not set up the plugin to create user accounts. Please read https://github.com/akeeba/sociallogin/wiki/Apple and check the settings for Create new user accounts, Ignore Joomla! setting for creating user accounts, and Bypass user validation

> I still have "invalid request" when I come back to the site after authentification including MFA from Apple.

The way you describe it that's something entirely different and it means that your server rejects the request. Talk with your host / systems administrator.

**Comment by GaetanLabrecque** [comment]
Hello Nicholas,

I have already read that and activated those options.  Here they are 

![settings apple plugin](https://github.com/akeeba/sociallogin/assets/33205353/7eca3561-2073-4dd9-8f51-f487ac8521e9)

**Comment by nikosdion** [comment]
Please read the second part of my reply.

**Comment by GaetanLabrecque** [comment]
Hello

I'm administering the service.  It is hosted on a provider.  I can call them but they will ask me why it is working for Microsoft and Google and not Apple.

**Comment by GaetanLabrecque** [comment]
When I go into membership pro, I can check the user and I have an option to link the account with apple.  When I do that  I get  "invalid_request" Invalid web redirect url.  So I will double check my configuration in apple.

**Comment by nikosdion** [comment]
See, that's more context I was not provided and yes, this means the setup on Apple's side is wrong. Your redirect URL is wrong.

The way you phrased it before, it sounded like you got the server error page for HTTP 400 Invalid Request which is something completely different, and has to do with the server configuration (typically, either something in the .htaccess file, or something with the mod_security2 configuration on the server).

**Comment by nikosdion** [comment]
NOTE: The underscore makes a **massive** different in providing me context. The underscore makes me think "OAuth2 error response". No underscore makes me think "web server error page".

**Comment by GaetanLabrecque** [comment]
I just verified and my return url is ok.  It is exactly like I saw on your explanation page.  The only exception is I used https and not http because apple would no accept it.

https://3demochiro.com/index.php?option=com_ajax&group=sociallogin&plugin=apple&format=raw

So I don't know

**Comment by GaetanLabrecque** [comment]
![Link options](https://github.com/akeeba/sociallogin/assets/33205353/9b6e4a69-5c18-48fe-97b1-b3399a520374)
This is where I'm trying to connect. Other informations I saw is if I click on link to google, I receive an error message saying error 400 : redirect_uri_mismatch.
If I click on link to Microsoft it works

However, I'm able as a user to connect  with a google account.  in my client access page.

Very strange, I continue to check

**Comment by GaetanLabrecque** [comment]
I see you have been able to create and account and link it with Google on our site.   I have been able to do this with my Google and Microsoft accounts

**Comment by GaetanLabrecque** [comment]
I did some tests (deleted account).  So I redid from scratch.  So, when I start from scratch, 

1. I choose login with apple
2. I go to apple, enter login name, password, I authorize
3. Then I come back to site.  I receive the error " You do not have an account on this site that corresponds to this Apple ID"
So, my understanding is, it is like the plugin is unable to create the account.

So, I tried to create the account first and try to login using apple id that correspond to the email of the account I just created.
I get "invalid request"

If I go into the user profile, in the social login tab and click on link apple, I get  Invalid_request.  Invalid web redirect url.

So, I really don't know what to do next.

Gaetan

**Comment by nikosdion** [comment]
I found out two problems.

1. Joomla! 5 introduced some changes in the way user sessions work, making the session token randomly reset. This is what leads to random "Invalid request." replies. If you persist you would get the correct error, that no user exists on the site. This has been addressed by using a different token generation.
2. Apple does **NOT** provide user authentication claims in the returned JWT token when you log into your Apple ID over the web (as opposed to using a Mac, or iOS/iPadOS device with built-in authentication). This is why a new account could not be created. Since Apple is now enforcing 2FA on all accounts when logging in from the web I removed that check.

You can download and install the following dev release: https://www.akeeba.com/download/sociallogin-dev/4-8-0-dev202404180950-rev7120207.html

If you want to verify it's working before installing it, you can use the demo installation at https://myoldsite.com/

Please let me know of your results.

**Comment by GaetanLabrecque** [comment]
Hello NIcholas,

From what I can see, it seems to work.

I still have to run full tests with the solution to be sure.  I will get back to you.

Thank you very much for your help

Gaetan
________________________________
De : Nicholas K. Dionysopoulos ***@***.***>
Envoyé : 18 avril 2024 09h03
À : akeeba/sociallogin ***@***.***>
Cc : Gaetan Labrecque ***@***.***>; Author ***@***.***>
Objet : Re: [akeeba/sociallogin] Unable to make work the sign with apple option (Issue #115)


I found out two problems.

  1.  Joomla! 5 introduced some changes in the way user sessions work, making the session token randomly reset. This is what leads to random "Invalid request." replies. If you persist you would get the correct error, that no user exists on the site. This has been addressed by using a different token generation.
  2.  Apple does NOT provide user authentication claims in the returned JWT token when you log into your Apple ID over the web (as opposed to using a Mac, or iOS/iPadOS device with built-in authentication). This is why a new account could not be created. Since Apple is now enforcing 2FA on all accounts when logging in from the web I removed that check.

You can download and install the following dev release: https://www.akeeba.com/download/sociallogin-dev/4-8-0-dev202404180950-rev7120207.html

If you want to verify it's working before installing it, you can use the demo installation at https://myoldsite.com/

Please let me know of your results.
