### ISSUE TITLE
Is there possible to contribute with a provider which is not oauth?

### ISSUE THREAD

**Issue by jaanusnurmoja** [akeeba/sociallogin#116]
My intention is to create a national id card login feature for my Joomla website which will not depend on external oauth-like services as my host provider has a built-in id card login feature. This is enabled for subdomains called id (while my site is mydomain.ee or mydomain.ee/mysite or mysite.mydomain.ee, id card login is possible against id.mydomain.ee 

If I browse https://id.mydomain.ee, it prompts me to (choose a right certificate and then) submit pin code related to my id card (this is from id-card software) and gives access after succesful authentication. It's just up to me what kind of output I want from the $_SERVER SSL variables there (incl. do I want to use such things like client id / client secret or not). 

I configured the index.php to meet my requirements so that I get after succesful authentication

`{"firstname":"JAANUS","lastname":"NURMOJA","pno":"PNOEE-36706230000","idcode":"36706230000","email":"36706230000@eesti.ee","country":"EE"}`

The potential plugin would make a request against this id-card service and after the person succesfully identified itself, do the same with the response that other sociallogin providers do (map with Joomla user data, create new user if missing and login). As it should be clear, **only one request uri is needed** (i.e https://id.mydomain.ee) and **there is no consent screen**.

Thanks in advance!

**Comment by nikosdion** [comment]
I do not think that using SocialLogin makes sense in this use case.

You can just create a login button plugin for Joomla!. Your use case is far similar to WebAuthn than it is to OAuth2. Look at the Joomla WebAuthn plugin to understand the steps it uses to log a user in.

**Comment by jaanusnurmoja** [comment]
But, let's say "Custom openid"? I mean that site owner is aware against which openid service exactly the authentication should happen, submits the corresponding url in admin form, e.g https://openid.ee etc and then auth goes this way.
Example image - consent screen after identification with id card against https://openid.ee
![image](https://github.com/akeeba/sociallogin/assets/1138055/5492b594-1c74-4e6f-8340-0aaa1a0c5071)

**Comment by nikosdion** [comment]
Why don't you just **TRY**?!

**Comment by nikosdion** [comment]
To make it clear: OpenID Connect, the web standard, is build atop OAuth2. You explicitly told me that what you want to do does not involve OAuth2. Then you show me something in a language I can neither speak nor read which looks very much like an OAuth2 consent page.

Even if I could read your language, the fact remains that your national identity card provider is something I cannot use as I am not a national of your country. Therefore, you have to try writing the code yourself. Don't expect a magic solution to appear wholly formed in front of you. You asked about contributing, not about having the work done for you, and I answered you based on the info you gave me about something I cannot possibly know anything about.
