### ISSUE TITLE
Error integrating akeeba social login 

### ISSUE THREAD

**Issue by GaetanLabrecque** [akeeba/sociallogin#117]
Hello

My dev is trying to integrate akeeba social login into membership pro. We are using your instructions provider and it is not working.
echo \Joomla\Plugin\System\SocialLogin\Library\Helper\Integrations::getSocialLoginButtons();

We are receiving Class "Joomla\Plugin\System\SocialLogin\Library\Helper\Integrations" not found

So you know what could be wrong?

Thank you

**Comment by nikosdion** [comment]
Considering it's April 2024, I don't think you are building a new site based on Joomla! 3 which became End of Life in August 2023. Therefore, the problem is that you're looking at the Joomla! 3 instructions which don't work for Joomla! 4 and 5. In fact, a bit further down I have written this:

> As noted, our code DOES NOT render the login buttons in Joomla 4. Our code simply responds to the onUserLoginButtons event which was added in Joomla 4. Plugins responding to this event convey all the information Joomla needs to render additional login buttons such as WebAuthn (included in Joomla), SocialLogin etc.
> 
> If your extension does not render these buttons please talk to its developer. They need to update its code for Joomla 4. There is nothing you can do with an override.

**Comment by GaetanLabrecque** [comment]
Thank you Nicholas,

I will give the information to my dev

Have a great day.

Gaetan
________________________________
De : Nicholas K. Dionysopoulos ***@***.***>
Envoyé : 5 avril 2024 09h28
À : akeeba/sociallogin ***@***.***>
Cc : Gaetan Labrecque ***@***.***>; Author ***@***.***>
Objet : Re: [akeeba/sociallogin] Error integrating akeeba social login (Issue #117)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Considering it's April 2024, I don't think you are building a new site based on Joomla! 3 which became End of Life in August 2023. Therefore, the problem is that you're looking at the Joomla! 3 instructions which don't work for Joomla! 4 and 5. In fact, a bit further down I have written this:

As noted, our code DOES NOT render the login buttons in Joomla 4. Our code simply responds to the onUserLoginButtons event which was added in Joomla 4. Plugins responding to this event convey all the information Joomla needs to render additional login buttons such as WebAuthn (included in Joomla), SocialLogin etc.

If your extension does not render these buttons please talk to its developer. They need to update its code for Joomla 4. There is nothing you can do with an override.

**Comment by GaetanLabrecque** [comment]
And yes, we are using joomla 5

Thank you
