### ISSUE TITLE
Cannot use object of type ReflectionProperty as array

### ISSUE THREAD

**Issue by sluc69** [akeeba/sociallogin#118]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Be specific. You may link to one or more screenshots or a video as long as it's not the only clue you leave. Use words to describe what happens.

### Expected result

What you believed should have happened following the steps you outlined above.

### Actual result

What actually happened.

### Troubleshooting already performed

Please tell us about any troubleshooting you already performed and its results.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: x.y.z
* **PHP version**: x.y.z
* **Am I using HTTPS**: Yes or No
* **Server Operating System**: Windows, Linux, macOS, Don't Know
* **My device's Operating System**: Windows, Linux, macOS, iOS, Android...
* **My device's Operating System version**: e.g. macOS Mojave
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera, ...
* **Browser version**: x.y.z

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: x.y.z
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Server version**: x.y.z
* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea.

**Comment by sluc69** [comment]
Plugin settings:
![Screenshot 2024-05-06 131045](https://github.com/akeeba/sociallogin/assets/82952282/35ade72c-2389-4aa0-b7e6-bc42825ecf80)
![Screenshot 2024-05-06 130754](https://github.com/akeeba/sociallogin/assets/82952282/d8e1594f-344f-45e5-a0f5-e2ab9a4bc83a)

Setup google according your document https://github.com/akeeba/sociallogin/wiki/Google

If I login 
![Screenshot 2024-05-06 131230](https://github.com/akeeba/sociallogin/assets/82952282/879ec2f7-241e-4cab-b5d5-d00e9601cba5)

I get this
![Screenshot 2024-05-06 131303](https://github.com/akeeba/sociallogin/assets/82952282/1112470e-029f-4e2a-bc99-3e51f4f3599f)

The user is added and activated. If i disable or delete the user, the error disappears 
[systeminfo-2024-05-06T05_17_23+00_00.txt](https://github.com/akeeba/sociallogin/files/15216876/systeminfo-2024-05-06T05_17_23%2B00_00.txt)

**Comment by sluc69** [comment]
Invalid?? What do i do wrong??

**Comment by nikosdion** [comment]
You submitted an issue without filling in any fields, you sent three screenshots, then closed your issue. I assumed that you had resolved it yourself, which is why I marked it as invalid. It's standard practice when an issue does not contain any information which would be useful to someone in the future coming across it in a search. The invalid label will tell them "there's nothing for you here, move along".

For what it's worth, this does not look like something coming from SocialLogin. You can verify this by going to my dev site https://myoldsite.com/ and trying to log into it with your Google account.

To understand what is going on, you need to go to your site's Global Configuration and set Debug Site to Yes, and Error Reporting to Maximum. Reproduce the issue. You will now get a more detailed trace of the error. If you copy this trace here I will be able to tell you where the problem comes from.

**Comment by sluc69** [comment]
The problem is with the "System - Akeeba Social Login"
What is the purpose of the "User group ...." settings?
If i leave it to "Not Assigned" all works fine. I had the impression I should select "registered" as this is the normal user group I assign for "registered users". But it is already set to "registered" without this setting.
Thanks for your time.

**Comment by nikosdion** [comment]
Debug backtrace. Where is it?

Other questions are answered in the documentation.

**Comment by nikosdion** [comment]
And by documentation in this case I mean click on Toggle Inline Help.

> **User Group when social network account is linked**. Add the user to this Joomla User Group dynamically when they have linked their Joomla user profile with a social network account. The user group assignment is only valid throughout the login session and is NOT stored in the database.
>
> **User Group when social network account is NOT linked**. Add the user to this Joomla User Group dynamically when they have NOT linked their Joomla user profile with a social network account. The user group assignment is only valid throughout the login session and is NOT stored in the database.

The idea is showing / hiding content depending on whether the user has linked their account to a social login provider. Here's how. Create a user group "Antisocial Group" and another user group "Social Group". No further settings for each group. Create two View Access Levels. One is "Antisocial" which only has the "Antisocial Group" in it. The other is "Social" which has the "Social Group" in it. Let's say you want to only show some information to people who have an active social network login in their user account: publish that content with the Social view access level. If you want to display some information, e.g. a callout to link social accounts, only to people who do NOT have an active social network login in their user account: publish that content with the Antisocial view access level.

**Comment by sluc69** [comment]
Ok!
Thanks for the explaination

**Comment by nikosdion** [comment]
Regarding the reflection issue, the necessary change is here: https://github.com/akeeba/sociallogin/commit/482e0f32f04a019f4fc9c3170a0ce82cfb8cbef4#diff-63b6aa169ccb89d5a587f1d72108c4e5b63a81b2fb17ed6006f3f3bf06aeadd2 A new version will be released next week. In the meantime, if you do need the dynamic user groups feature, you can just make the one line change.

Regarding the documentation, while I had documented the two options in the plugin, I realised when replying to you that it might not have been very clear what they are meant to do. I added far more detailed documentation here: https://github.com/akeeba/sociallogin/wiki/The-system-plugin#using-the-dynamic-user-groups As you can see, it's a mighty powerful feature allowing for great customisation of the user experience depending on their social login status. I actually did have a use case like that, on a site which was transitioning to Login with Google for its volunteers (not very tech literate; they are philologists in their 60s and 70s) and needed to take them by the hand during the transition. The example I give in the documentation, only allowing comments to people with a social login linked, is something that has been asked in the past; the user would only allow their organisation's Microsoft accounts to log into the site, and wanted to limit posting comments to its staff, but have them visible publicly. One feature to rule them all, I guess :)
