### ISSUE TITLE
Integration with other domain

### ISSUE THREAD

**Issue by programmerIhor** [akeeba/sociallogin#119]
I have a site, say domain.com, which uses Joomla with akeeba social login plugin, and I also have another site, say another-site.com, which uses custom php scripts for authentication on domain.com to use the same users database, is it possible to somehow provide the same google (or any other OAuth method) authorization in such a way that it works both ways, because now I have it working only in one direction and I would appreciate if you could help me with this or just tell me that it is not possible?

**Comment by nikosdion** [comment]
If I understand correctly, you want to be able to log into either site with Google and be logged in to the other site as well. Nope, this won't work.

**Comment by programmerIhor** [comment]
There was a misunderstanding, I explained it wrong. 
So, what I have now:
1. A page that uses Joomla and Akeeba Social Login
2. Another page written in React that uses the custom scripts from the first page for authentication
3. Users can login with google from both of these pages
4. Users can sign up with google from both of these pages
5. Users signed up with google on the second page (React page) can sign in with google on both pages

What is the problem:
When users are signed up on the first page (Joomla page) using google, they can't login to the second page (React page) and I want to clarify if it is possible to actually synchronize users using google to login from both pages without any custom scripts?

Thanks for your reply and best regards

**Comment by nikosdion** [comment]
No, it is not possible to magically synchronise users between two sites (a page and a site are different things) without writing any code. I should think the privacy, security, and legal implications of it being otherwise would be blatantly obvious.
