### ISSUE TITLE
Translate login button text

### ISSUE THREAD

**Issue by Giorgi625** [akeeba/sociallogin#121]
Hello I can not find where to translate text in button. I have multilanguage website where I have enable login with Google and plan to add also facebook. 
Google button has : Sign in with Google
Where can I translate it?

**Comment by nikosdion** [comment]
It's standard Joomla language strings for each plugin in the sociallogin group. Please consult Joomla's documentation on creating language overrides through the backend interface. 

IMPORTANT! Language files for plugins are always backend language strings BUT your language overrides must be set for both the backend and the front-end. It is stupid, but that's the way Joomla works for historical reasons which can be traced back to mambots back in 2003 (or was it 2002? It's been a while…).
