### ISSUE TITLE
Add support for Auth0

### ISSUE THREAD

**Issue by finchr** [akeeba/sociallogin#122]
**Is your feature request related to a problem? Please describe.**
I would like Auth0 to be added to the Social Login plugins so I can user Auth0 to login to my Joomla site.

**Describe the solution you'd like**
Create a new plugin for Auth0 that can be enabled and configured like the others.

**Describe alternatives you've considered**
The [Synology](https://github.com/akeeba/sociallogin/wiki/Synology) plugin is almost flexible enough with similar configuration options to allow an Auth0 authentication. Maybe create a generic oauth plugin?

**Why do you think this is relevant to people other than you**
Auth0 has a big user base.

**Additional context**
I looked at several other plugins (some of which are kinda pricy) that provide this kind of functionality and this one is the best1

**Comment by nikosdion** [comment]
Closing the issue since the PR is already merged.
