### ISSUE TITLE
Integration with SEBLOD

### ISSUE THREAD

**Issue by joomla-ua** [akeeba/sociallogin#14]
Please create integration with SEBLOD.
THANKS!

**Comment by nikosdion** [comment]
Social Login allows you to log into your Joomla! site using a user account provided by a social network. SEBLOD is a component for Joomla!. If you want to "log into Seblod" you actually just need to log into Joomla!. Therefore Social Login does what you apparently want it to do. As a result I have to close this issue as invalid.
