### ISSUE TITLE
No tweeter and google plugin after install

### ISSUE THREAD

**Issue by micker** [akeeba/sociallogin#15]
### Steps to reproduce the issue

Install 1.1 package

### Actual result

we only have facebook integration plugin no google and no tweeter

### System information (as much as possible)
* **Joomla! version**: 3.7.5
* **Database type**: MySQL
* **Server type**: Apache
* **Server version**: x.y.z
* **Hosting company / Local server**: 1&1
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **Server Operating System version**:  N/A. 
* **Browser**: Chrome,

**Comment by nikosdion** [comment]
Thank you very much for the heads up! I released version 1.0.2 which fixes this packaging issue.
