### ISSUE TITLE
Get Profile Pic (possible enhancment)

### ISSUE THREAD

**Issue by navjinder** [akeeba/sociallogin#22]
Is it possible to save profile picture from Facebook and Google?

**Comment by nikosdion** [comment]
No, for several reasons.

First of all, this is a login solution, not a user profile solution. It’s meant to let you log in with something other than a username and password. It could be your Facebook account but it could also be a PIV smart card. Not everything has a profile picture attached, therefore that would create a feature asymmetry. 

Moreover, as I have explained in another request for the same feature, Joomla does not provide an API for profile pictures. Every component that has support for profile photos has a different API. This means at least six different plugins per login method. If I were to do that I’d be spending hundreds of hours developing this and I’d be asking for at least 100€ per login method to justify the time spent. However, I’m not sure anyone would pay that for a profile picture :)

So, first try to get Joomla to introduce a profile picture API, then convince all third party developers to use it, then it’s dead easy to pull it from linked social media profiles and we can talk about it again, for a companion –but separate– product to SocialLogin. Good luck with the first part. I’ve tried to get easier things included in Joomla, like SocialLogin itself, and got so much pushback I decided to basically say screw it and do my own thing.

**Comment by navjinder** [comment]
Wow thanks for the explaination. You are right in every sense that an api
for profile pic is not part of Joomla and I was not aware about the time
and effort that goes into just getting the workaround. I am happy with your
plugin its just do the task and add no bloatware to the system. Kudos to
you for that.

In that case I am thinking of coding a solution myself i.e. pulling the
profile pic url into the new extrafields in Joomla.

Thanks for your reply and honesty.

On Nov 3, 2017 2:03 AM, "Nicholas K. Dionysopoulos" <
notifications@github.com> wrote:

No, for several reasons.

First of all, this is a login solution, not a user profile solution. It’s
meant to let you log in with something other than a username and password.
It could be your Facebook account but it could also be a PIV smart card.
Not everything has a profile picture attached, therefore that would create
a feature asymmetry.

Moreover, as I have explained in another request for the same feature,
Joomla does not provide an API for profile pictures. Every component that
has support for profile photos has a different API. This means at least six
different plugins per login method. If I were to do that I’d be spending
hundreds of hours developing this and I’d be asking for at least 100€ per
login method to justify the time spent. However, I’m not sure anyone would
pay that for a profile picture :)

So, first try to get Joomla to introduce a profile picture API, then
convince all third party developers to use it, then it’s dead easy to pull
it from linked social media profiles and we can talk about it again, for a
companion –but separate– product to SocialLogin. Good luck with the first
part. I’ve tried to get easier things included in Joomla, like SocialLogin
itself, and got so much pushback I decided to basically say screw it and do
my own thing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akeeba/sociallogin/issues/22#issuecomment-341627956>,
or mute the thread

**Comment by navjinder** [comment]
Hi Nik

Ok I have found a solution where you can always directly pull the image from facebook. 

In the file `system/sociallogin/helper/login.php` I have added this fuction

```php	
public static function getProfilePic($slug, JUser $user = null)
	{
		// Make sure there's a user to check for
		if (empty($user) || !is_object($user) || !($user instanceof JUser))
		{
			$user = JFactory::getUser();
		}

		// Make sure there's a valid user
		if ($user->guest || empty ($user->id))
		{
			return false;
		}

		$db    = JFactory::getDbo();
		$query = $db->getQuery(true)
		            ->select('profile_value')
		            ->from($db->qn('#__user_profiles'))
		            ->where($db->qn('user_id') . ' = ' . $db->q($user->id))
		            ->where($db->qn('profile_key') . ' LIKE ' . $db->q('sociallogin.' . $slug . '.userid'));

		try
		{
			if($slug === 'facebook'){
                               $profileurl = '//graph.facebook.com/'.$db->setQuery($query)->loadResult().'/picture?type=large'; //option could be added for profile pic size 'normal', 'large' or 'small'
                       }else{
                        //not sure about google url
                             $profileurl = '';
                      }

			return  $profileurl;
		}
		catch (Exception $e)
		{
			return  ''; //or return a default profile pic
		}
	}
```

Then I am calling 
```php
if (class_exists('SocialLoginHelperIntegrations')) echo SocialLoginHelperIntegrations::getProfilePic();
```
on profile override and logout override page. I hope this will help someone else. Let me know if you like these changes I can send you a PR.

Thanks

**Comment by nikosdion** [comment]
I *WOULD NOT* put that method in the SocialLoginHelperIntegrations class for quite a few reasons.

First of all, you are doing a *CORE HACK*. This means that you will never be able to update the software. This is an obvious problem. If you don't understand it, ask me and I'll explain.

Second, you have no clue about software architecture, do you? The SocialLoginHelperIntegrations class is a helper class for *COMMON, ABSTRACT, LOGIN-PLUGIN-AGNOSTIC* code. Your code is not abstract. it is currently 100% tied to a specific login plugin. If you need to add support for other login plugins you have to edit the code. See above note for core hacks.

The architecturally sound way to do that is by adding a plugin event to each *and every* SocialLogin plugin. Let's say that we added a method "onSocialLoginProfilePicture" which either returns null or a simple array in the form `[ 'method' => 'facebook', 'url' => 'https://.........'  ]`. Now _this_ is something someone could use in their code. They'd just trigger the onSocialLoginProfilePicture plugin event and parse the returned array in a way that makes sense in the context.

However, as I said, this is not an acceptable solution for me because there is no API for returning profile pictures in Joomla!. Every component that needs a profile picture implements its own API. Adding Yet Another Bespoke API to do the same thing doesn't sound like a good idea. More so since I've been there, done that (with Akeeba Subscriptions and Akeeba Ticket System) and I can see that exactly ZERO other developers were eager to adopt it.

So, where does that leave us? You have written a method which works _for the very narrow scope you have_. Obviously, you are using this code somewhere, presumably in a plugin or component of your own. So instead of hacking core and making it impossible to update my software why don't you put that code in your software where it belongs? Sure it has a hard dependency on the _data_ put in the generic purpose Joomla! user profile fields database table, but that's not a problem. If the data is not present it can either return blank (as you do now) or fall back to Gravatar (since you already know the user's email).

Don't just hack your way to a solution. Think about the impact of your actions before you lay a finger on the keyboard to write code. That's what separates coders from software developers.

**Comment by navjinder** [comment]
I know Nik this is a core hack therefore I have created my own plugin. I
know when social login will update the function will be gone. Working in
Joomla for so many years has tought me that. All I want for my website is
to display the user profile pic on the logout page and user profile page
because facebook login is the only way the client needs users to login. I
do not want to store the images of the users on the server. As the latest
profile pic should be pulled each time.

I was asking for the PR if you want this function to be added to the plugin
because its a social login plugin thereofore makes sense to have atleast
something to show/display the profile pic. It's ok you are right this is
not how software architecture works but it's how I have solved a problem
for my client's website. I was just informing for the the record  that this
is what my need was and this is what I have done to achieve it.

You are an amazing dev with outstanding eye for code and I respect what you
do. With Akeeba you have made life of many developers a lot easier
including mine. I am sorry if I have offended you. I was trying to fix a
small problem(for my needs) and maybe if someone else is looking for
similar solution they could have some idea to how to solve it.

Happy Coding.

**Comment by nikosdion** [comment]
> I know Nik this is a core hack therefore I have created my own plugin

Perfect! Then you can just pull in the code you wrote into your plugin :)

> I was asking for the PR if you want this function to be added to the plugin

I had already replied why I didn't want to do that (at least not yet) earlier in the conversation. Also, you putting some code in a comment is not a PR. I was genuinely confused and thought you had modified the copy of the plugin on your site which would've been, well, problematic :D 

>  I am sorry if I have offended you.

Not at all. I just want to make sure that your code ends up where it belongs architecturally (your plugin) and your site is maintainable with the least amount of effort.

> its a social login plugin thereofore makes sense to have atleast something to show/display the profile pic

Just to make it clear: the marketing name is SocialLogin. The actual goal is to provide a framework for alternate authentication methods which are not based on entering a username and password. Right now, Joomla's login page and module is only good for logging in with your Joomla! username and password or via LDAP authentication. Everything else has moved to OAuth2 or some other similar API. This is what I want to provide with this plugin.

Moreover, there are other passwordless authentication methods. For example, W3C has already introduced the Web Authentication standard (formerly FIDO 2.0). You can learn more about it in issue gh-17 on this repository. It basically boils down to logging into your site with your face, fingerprint, smartcard or whatever trusted authentication mechanism is supported on your computer. As you understand, authentication methods like _that_ do not offer any way to get a profile picture.

Furthermore, there is the obvious question: if I have set up five authentication methods which all provide a profile picture, _which one_ do I want to display on the site? I can tell you how this can be solved architecturally.

The plugins need to have an event to provide a short structure with the login method name, the human readable name and a profile picture URL (or several, if there are different dimensions available). Then we need to write a custom field class to let a user choose interactively which one they prefer in their user profile. This field would be injected by our main plugin, just like we do for the link / unlink buttons. The result would be saved in the user profile parameters. Then we need another plugin event in the main plugin which is given a user ID and a desired size in pixels and returns the profile picture URL.

Now, this last plugin event is something that Joomla! has to standardize. Until they do there's little point writing our own. That's my whole point.

So, there. It's not like I don't want to write this code. I'm mostly concerned that writing this code will be in vain. Maybe if I have time I can also write a content plugin which allows you to inject the user profile photo easily in content. Well, I guess I could add a low priority feature like that.
