### ISSUE TITLE
Profile photos

### ISSUE THREAD

**Issue by nikosdion** [akeeba/sociallogin#23]
# Summary

* Allow login methods to (optionally) provide user profile URLs.
* Let the user choose which user profile picture to use, in case there are several available.
* Create a content plugin which allows the site admin to inject user profile information (first/last name, name, username, email, profile photo, any profile field by name) into the content either by use of a merge code or by use of a static method call.

Note: See gh-22 for the conversation that led here.

# Architecture

## `sociallogin` plugins

Each login method plugin needs to have an event which provides a login picture. For example:
`public function onSocialLoginGetProfilePictureInternal($userID, $size = 64)`
where `$userID` is the numeric ID of the user and `$size` is the desired size in pixels. If the plugin cannot return profile pictures or the user hasn't linked his profile with this plugin return null. If the requested size is not available return the immediately larger one or, if the requested size is beyond our capabilities, the largest available. The return format is:
```php
[
    'plugin' => 'foobar',
    'url' => 'http://www.example.com/profile?u=0123456789abcdef0123456789abcdef'
]
```

## `sociallogin` plugin for Gravatar

We need to create a plugin which does not allow login but just provides a Gravatar profile picture as a safe fallback.

## `system` plugin

The `onContentPrepareForm` needs to inject yet another field whcih allows the user to select which profile photo they'd like to use on the site.

This means that we need to provide another custom field class which renders a dropdown image selection box. We have to check if there is a Joomla! layout that already does that. If not, just revert to offerring a list of plugin names.

In either case you can get the list of active plugins with profile picture capability and the profile picture itself by triggering the `onSocialLoginGetProfilePictureInternal` plugin event and weeding out the empty results.

The System plugin will also offer the event `onSocialLoginProfilePicture($userID = null, $size = 64)` to retrieve the applicable profile picture URL for the given user. If the user is given as null or 0 then, obviously, we use the currently logged in user.

## `content` plugin

It uses the `onContentPrepare` plugin event to parse the following content tags:
* `{sociallogin:button plugin}` Return the HTML for the button to login a user via Social Login using the specified plugin (e.g. `facebook`). If the user is logged in display nothing.
* `{sociallogin:picture [user]}` Return the profile photo. `user` is optional and can be a username of numeric user ID.
* `{sociallogin:userinfo item [user]}` Return a piece of user information. Item can be id, email, username or the name of any user profile field.

## `ats` plugin

Expose the social login profile photo to Akeeba Ticket System.

**Comment by navjinder** [comment]
Wow thanks Nik for adding it to the roadmap; you are truly awesome. 👍

**Comment by nikosdion** [comment]
I see a few major issues:

* Not all platforms offer a permanent avatar URL. For example, Facebook only offers a URL which will expire within a few hours.
* Some platforms do not offer an avatar URL at all.
* Those which do typically require additional permissions from the user to send an avatar URL.

This defeats the purpose of this feature. So, I guess, it can't be implemented after all :(
