### ISSUE TITLE
Facebook Integration Plugin Settings - Bypass User Validation for Verified Facebook Users 

### ISSUE THREAD

**Issue by esskay303** [akeeba/sociallogin#24]
### Steps to reproduce the issue

1. Joomla user option - New user account activation - Set to Self
2. Bypass user validation for verified facebook users - Set to Yes
3. Login with Facebook
4. User created in Joomla and an email is sent to activate the account

Make sure your issue can be reproduced on a new installation of Joomla! without any modified configuration settings or third party extensions. If the issue only occurs with a specific third party extension or configuration setting please specify exactly what triggers it. Always keep in mind that if it can't be reproduced it can't be fixed!

### Expected result

User should have been logged in without activating his account in the email

### Actual result

User asked to first verify his email

### System information (as much as possible)
* **Joomla! version**: 3.8.1
* **Database type**: MySQL
* **Database version**: 5.5.58-0+deb8u1
* **Server type**: Apache
* **Server version**: 2.4.10
* **Hosting company / Local server**: Digital Ocean
* **Am I using HTTPS**: No
* **Server Operating System**: Linux
* **Server Operating System version**: Debian 
* **Browser**: Chrome
* **Browser version**: 61.0

**Comment by nikosdion** [comment]
Cannot reproduce. Is the user verified *on Facebook*? That is, does the user have a _verified_ email address or a _verified_ phone number on Facebook? If Facebook tells us that the user is not verified we can't activate the user. Also note that, by default, Facebook doesn't verify either.

**Comment by esskay303** [comment]
Yes...the user is verified in the facebook. It is a fresh installation on a test site. Do you want link and admin access...?

**Comment by nikosdion** [comment]
Thank you for the heads up. The problem was with a mistyped capital letter. The fix will be applied in the next version, 1.0.3.
