### ISSUE TITLE
Missed language string in System - Akeeba Social Login

### ISSUE THREAD

**Issue by Sulpher** [akeeba/sociallogin#26]
There is missed en-GB language string in System - Akeeba Social Login
PLG_SYSTEM_SOCIALLOGIN_CONFIG_BACKENDLOGINMODULES_LABEL

ver.1.0.2

![screen shot 2017-11-13 at 17 50 45](https://user-images.githubusercontent.com/3432048/32731658-78e5158a-c89b-11e7-9285-81159211537f.png)

**Comment by nikosdion** [comment]
Thank you for the heads up! I had actually fixed it a few weeks ago but there was no published version yet including the string :)
