### ISSUE TITLE
login autentification popup

### ISSUE THREAD

**Issue by technoparck** [akeeba/sociallogin#31]
hello
i have used your social lgin plugin in the site , and i want as if it's possible to oppen the social autentification pages in popups like here https://getk2.org/connect   also for example when you click on facebook or google buuton you will see the popup , this is what i want , how can i do this in your plugin ?

thanks

amine

**Comment by nikosdion** [comment]
No and for a good number of reasons. Off the top of my head:

* Popup and ad blockers will prevent that popup from opening. Our software works with the major ad / popup blockers out of the box.
* Popups are not mobile friendly. Our software is mobile friendly.
* Popups do not solve any problem; you still need to reload the page to enforce the user login. Our software prefers to be simple and robust than unnecessarily fancy and fragile.
* Cross-domain requests with popups require you to set up CORS. Failure to do so would give the impression the product is broken when, in fact, the browser does exactly what it's supposed to do (block cross-domain requests on a popup!). Our software requires zero server configuration (all you need to do is have cURL enabled).
* Popups rely on Javascript to log you in. Our software works without JavaScript (as long as the login provider supports JavaScript-less operation).

Popups was how things were done back in 2011. Unfortunately, K2 and its site have remained in that olden era and never really caught up to modern web development. I wouldn't exactly use them as an example of what to do but rather as an example of what to _avoid_.

**Comment by technoparck** [comment]
ok thanks for the infos

i will not use the popup from now ..

thanks
amine

**Comment by technoparck** [comment]
hello

i use the social login plugin on the Site but i have a small on login with
twitter also if i turn on the option Create new user accounts but it still
give me the error "
Warning

You do not have an account on this site that corresponds to this Twitter
account.

"

this is screen of the otion used https://www.screencast.com/t/Z2A3nq0j8
and it work on facebook and google also users can login using them withawt
have account with the emain on the site but in twitter not



how can i fix this please ?



thanks

amine

**Comment by nikosdion** [comment]
I don't want to sound dismissive, but have you tried reading [the fine manual](https://github.com/akeeba/sociallogin/wiki/Twitter)? I have a paragraph explaining exactly that. Copied and pasted here:

> IMPORTANT If you want to allow people who have NOT already linked their Joomla! user account with their Twitter profile to log into your site and / or create a new user account you must follow the instructions in this paragraph. Edit your Twitter application and fill in both the Privacy Policy and Terms of Service fields. Then first save the changes to your Twitter application, then edit it again. Go to the Permissions tab, scroll down and tick the "Request email addresses from users" box. Click on the Update Settings button to save your changes. Please note that if you do not that Twitter will not send the user's email to Joomla!, therefore logging in an unlinked account or creating a new user account will be impossible as in both cases the email address is required.
