### ISSUE TITLE
Message you are not authorised to view this resource on login

### ISSUE THREAD

**Issue by harrolds** [akeeba/sociallogin#32]
I have a problem with the "You are not authorised to view this resource" message after login with google or facebook. I thought it might be because of my template or extra components/modules so i decided to test it on a complete clean installation with no modules or anything activated. The only thing i have changed is the fact that new users don't have to activate there account. The website can be viewed/tested here: www.motor2go.nl/test/

The exact steps are:

- Click on the menu link Login
- Click on the Google button
- Select my google account which to use for login
- Automatically return to the website where i am then logged in but see the message "You are not authorised to view this resource"
- Click f5 for page refresh and the message is gone. 

All the time the website is working as expected. Also, when i login with my normal credentials through the Joomla login i do not get to see the system message.

Expected result:
Login without the system message

Actual result:
Login works but with message "You are not authorised to view this resource.

System information:
PHP gebouwd op | Linux vs28016 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64
-- | --
Database versie | 5.5.5-10.1.23-MariaDB
Database collatie | utf8_general_ci
Collatie van de databaseverbinding | utf8mb4_general_ci
PHP versie | 7.1.10-1+0~20170929170631.9+jessie~1.gbp501135
Webserver | Apache/2.4.10
Webserver naar PHP interface | apache2handler
Joomla! versie | Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
Joomla! Platform versie | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Gebruikersagent | Mozilla/5.0 (Windows NT 6.0; rv:52.0) Gecko/20100101 Firefox/52.0
Not using https
Hosting company: Mijndomein.nl

**Comment by nikosdion** [comment]
What is the URL you are on before logging in and the URL you are returning to (the one that displays the access forbidden)?

Do you have any menu items pointing to any com_users page including but not limited to Login and User profile? If so, provide screenshots of their configuration including the access level assigned to them.

Have you already linked your user account with the Facebook or Google login?

If you answered no above, provide screenshots with the configuration of all of your published SocialLogin plugins (system, user and the login methods). You may blank out the access keys.

**Comment by harrolds** [comment]
Hi, 

Thanks for taking time to respond. As for your questions:

URL before login: index.php?option=com_users&view=login&Itemid=108
URL after login: index.php?option=com_content&view=article&id=1&Itemid=101

No other menu links to any com_users pages except the below provided login and logout.

![login-setup](https://user-images.githubusercontent.com/36454763/36254391-39df22fa-124b-11e8-9d63-d176859ba359.jpg)

![logout-setup](https://user-images.githubusercontent.com/36454763/36254403-43061fdc-124b-11e8-9dec-ae7938516336.jpg)

I have not linked any useraccount with Facebook or Google account. These are completely new accounts based on the google and facebook login.

Below the screenshots of the plugins as requested:

![system-akeeba-social-login](https://user-images.githubusercontent.com/36454763/36254557-d4d42a12-124b-11e8-94ce-bfeb9cd1b5d3.jpg)

![google-social-login](https://user-images.githubusercontent.com/36454763/36254565-d965a4de-124b-11e8-8176-b52406b81e0f.jpg)

![facebook-social-login](https://user-images.githubusercontent.com/36454763/36254577-df146cc6-124b-11e8-8e14-e05238614948.jpg)

With regards,

Harrold

**Comment by harrolds** [comment]
I just noticed that the permission setting is not visible in the screenshots. 

The login permission is guest, the logout permission is registered and the home page permission is public.

**Comment by nikosdion** [comment]
> The login permission is guest

And that's why it doesn't work. Guest means "nobody can see this except not logged in users". However, this is the URL your login requests are originating from and the URL you are returned to after logging in. You need to set its permission to Public.

One simple way to do that without showing a login menu item to logged in users is to create a hidden menu with a Public login item. On your main menu create an Alias item pointing to the previously created login menu item and set its permissions to Guest. This means that the actual URL of the login page (generated by the hidden menu item) is valid for logged in users whereas the main menu item is only visible to non-logged-in guests.

In any case, this is how Joomla menu item ACLs work and outside the purview of our software. Therefore I'm closing this issue as invalid.

**Comment by harrolds** [comment]
That did the trick. Thanks for explaining where i went wrong.
