### ISSUE TITLE
Plugins for github, microsoft & linkedin?

### ISSUE THREAD

**Issue by planeten** [akeeba/sociallogin#35]
### Steps to reproduce the issue
Install akeeba sociallogin

### Expected result
Plugins for github, microsoft & Linkedin

### Actual result
Plugins for facebook, google & twitter

### Additional comments
Thank you for these plugins and the great documentation. The docs mention plugins for github, microsoft and linkedin but only facebook, google & twitter are installed it seems?

**Comment by nikosdion** [comment]
Dunno. The files are included in the package version 2.0.3, they are installed by it... Maybe you don't have the correct package version? Maybe you just need to install it twice?

**Comment by planeten** [comment]
Apparantly "Install from Web" installs 2.0.2. Manually installed 2.0.3 and now they show up

**Comment by nikosdion** [comment]
Thanks for the heads up! The problem was that the update source was saying the latest version is 2.0.2 when, in fact, it's 2.0.3. Fixed by merging development into master.
