### ISSUE TITLE
Problems with Twitter login

### ISSUE THREAD

**Issue by webgobe** [akeeba/sociallogin#36]
### Steps to reproduce the issue

The installation I have problems with has Akeeba Admin Tools and RS Firewall. Completely deleting (not just disabling) RS Firewall fixed the problem

### Expected result

After associate the user with the Twitter account - done - clicking on the Twitter icon in login module should work. (Works for Facebook, Google Plus and LinkedIn withouth problems)

### Actual result
Error
You are not authorised to view this resource.

 I suspect, that the problem might be the callback url:
http://www.abrandnewsite.com/mysite/index.php?option=com_ajax
(Of course I am using the correct one, not this example ;) )

### System information (as much as possible)
* **Joomla! version**: 3.8.7
* **Database type**: MySQL
* **Database version**: 5.6.38
* **Server type**: Apache
* **Server version**: x.y.z
* **Hosting company / Local server**: LiquidWeb
* **Am I using HTTPS**: Yes 
* **Server Operating System**: Linux (CentOS)
* **Server Operating System version**: Linux host.leftbrainhosting.net 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera - all browsers tested
* **Browser version**: latest versions for all

**Comment by nikosdion** [comment]
If Admin Tools blocks something you get a recorded security exception. There is nothing of the sort.

The only way I can reproduce it is trying to use Twitter login in the backend (administrator) on Joomla! 3.8.7 and later. In the frontend it works just fine. Most likely there's a typo in a callback URL somewhere.

Here's the thing. I do not see me having any spare time in the foreseeable future, i.e. until the end of 2018. If anyone wants to debug this and submit a PR, be my guest. In the meantime you can definitely use Twitter login for frontend logins. That part works just fine.
