### ISSUE TITLE
Facebook stopped working.

### ISSUE THREAD

**Issue by okanime** [akeeba/sociallogin#41]
### Expected result
Successful login

### Actual result
Error: "Warning
You are not logged into Facebook or you didn't grant permissions for this site to log you in through Facebook"

### System information (as much as possible)
* **Joomla! version**: 3.8.11

**Comment by nikosdion** [comment]
I tried this just now on my test site and it works. Your problem is unrelated to our extension. Make sure you are logged into Facebook, that you have granted permissions for the Facebook application and that your FB application is set up correctly. I cannot help you with any of that.
