### ISSUE TITLE
Login with Instagram

### ISSUE THREAD

**Issue by nikosdion** [akeeba/sociallogin#5]
Login with [Instagram OAuth API](https://www.instagram.com/developer/authentication/).

**Comment by fishjnet** [comment]
Hello,

Is the login with Instagram done?

**Comment by nikosdion** [comment]
No. When an issue progresses you will see the commits about the issue being logged here. If it's done, the issue will be closed with a reference to the commit that merged it to the development branch.

**Comment by fishjnet** [comment]
Ok thank you.

**Comment by nikosdion** [comment]
Instagram does not report the user's email address, see https://www.instagram.com/developer/endpoints/users/#get_users_self As a result we cannot use it to log in a user who has not already linked Instagram to their Joomla user profile, nor can we use it to create new Joomla user accounts. This does not satisfy the minimum required set of features for inclusion in SocialLogin. Therefore login with Instagram will not be developed.
