### ISSUE TITLE
Akeeba Social Login - error gmal login

### ISSUE THREAD

**Issue by omega20st** [akeeba/sociallogin#54]
Hello, 
I use Akeeba social login plugin in IKS Theme Joomla but have a issue with it . 

error gmail login  - Argument 1 passed to Joomla\Utilities\ArrayHelper::toString() must be of the type array, boolean given, called in /home/fxxxx/public_html/plugins/system/sociallogin/Library/Plugin/AbstractPlugin.php on line 499

I want users to have options to login forthe first time to the website automaticly with facebook and gmail account and their social login to be saved in my website as their login data.  But i cant understand where is my mistake  and have those errors

**Comment by nikosdion** [comment]
I cannot reproduce it with the current development branch. My best guess is that when I refactored the code to support both Joomla 3 and 4 I must have inadvertently fixed the issue you are experiencing. Please wait a few more days for me to release the new version of SocialLogin.

**Comment by omega20st** [comment]
Ok. Thank you for your replay

**Comment by nikosdion** [comment]
The new version has been published. Please [download](https://www.akeebabackup.com/download/official/sociallogin/3-1-0.html) and install it manually. There has been a change in the update servers; Joomla will not find the update to the new version automatically. Thank you in advance for your feedback about this new version!

**Comment by omega20st** [comment]
Thank you very much. Have a nice day

На вт, 23.06.2020 г. в 10:23 Nicholas K. Dionysopoulos <
notifications@github.com> написа:

**Comment by omega20st** [comment]
Good afternoon,
I'm sorry to bother you again, but I can't understand why I can't login with twitter and facebook to my site, using your plugin.for example twitter when click login with twitter it takes me back directly to the my site without log. Some ideas ?
Thank you in advance

**Comment by nikosdion** [comment]
Global Configuration. Set Debug Site to Yes and Error Reporting to Development. Retry logging in.

A few log file are generated in your Joomla logs folder (default: administrator/logs). You are looking for `sociallogin_twitter.php` and `sociallogin_facebook.php`. You will see what happened.

Most likely you set up the wrong redirect URIs in Twitter and Facebook. I can tell you with certainty they both work. I have them set up on a live site I use for development and Twitter is also set up on my blog.

**Comment by omega20st** [comment]
Thank you very much. Have a nice day
