### ISSUE TITLE
Login Social

### ISSUE THREAD

**Issue by tecnologieinformatiche** [akeeba/sociallogin#55]
Hi, when I log in with a social network, you do not redirect to the menu I have indicated, why?

**Comment by nikosdion** [comment]
Social login buttons on Joomla 3 cannot receive the redirection URL set up in the login module. Joomla does not offer this information to the plugin UNLESS you use a template override as explained in https://github.com/akeeba/sociallogin/wiki/Integrating-with-template-overrides#adding-login-buttons This is exactly the use case for which the template overrides documentation was written. 

This is not an issue with Joomla 4.0 beta 2 and later. It includes code I’ve written for the WebAuthn plugin which also allows third party plugins, like SocialLogin, to render additional login buttons, sending them the information about the login URL.
