### ISSUE TITLE
Group Mapping

### ISSUE THREAD

**Issue by Wh00ps13** [akeeba/sociallogin#58]
We are using Google Gsuite and running a Joomla webpage we already using the plugin for google intergration and works great. Only thing is we would like to have group mapping to link google Gsuite groups to Joomla groups.

**Comment by nikosdion** [comment]
This is out of scope for Akeeba SocialLogin. We only handle **authentication**. You are looking for a different product that would additionally let you retrieve all of the GSuite groups and map them to Joomla groups, then modify the user permissions on the fly and on the database on each login. That is a very, very different product than what we do here.
