### ISSUE TITLE
Error update release 3.2.1

### ISSUE THREAD

**Issue by tecnologieinformatiche** [akeeba/sociallogin#60]
Hi, when I installed version 3.2.1 joomla gave me this error:

Notice: Undefined property: Pkg_SocialloginInstallerScript::$packageName in /var/www/vhosts/exposmart.it/httpdocs/tmp/install_5f8580c7c6d11/script.sociallogin.php on line 325

The linkedin plug-in is not installed

thanks

**Comment by nikosdion** [comment]
The PHP notice has been there for a while but doesn't affect whether the LinkedIn plugin is installed or not.

The LinkedIn plugin is included in the package (plg_sociallogin_linkedin.zip file) and referenced in the XML manifest, just like all other plugins. 

If you extract the package and install the plg_sociallogin_linkedin.zip file it installs just fine.

I don't know why Joomla won't install it through the package. This looks like a bug in Joomla itself. Unfortunately there's not much else I can do about it.

**Comment by tecnologieinformatiche** [comment]
Hi, I solved with the installation. Now, however, the button is not seen as before and the language is not Italian
![Screen Capture_select-area_20201013155120](https://user-images.githubusercontent.com/51816586/95870253-94dbe480-0d6c-11eb-81c8-1e23198a2346.png)

**Comment by nikosdion** [comment]
We only ship English language files with our software. If you want to translate it to Italian or any other language you can, it's just regular Joomla language INI files. As for the display of the button, this is controlled by the plugin's options. You can of course change them per the documentation.

**Comment by tecnologieinformatiche** [comment]
Hi, I edited the .ini file and set the CSS flags but I still have problems. The language does not translate and the key does not change. Can you help me thanks?

**Comment by tecnologieinformatiche** [comment]
OK Solved thanks
