### ISSUE TITLE
The plugin loads MooTools in the frontend

### ISSUE THREAD

**Issue by obuisard** [akeeba/sociallogin#61]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

- Make sure the test site does not load MooTools on its public side.
- Enable the social login plugin
- Check the source code of the page where the social login buttons are present.
- Acknowledge that MooTools is loaded.

### Expected result

The plugin should not need MooTools, as it uses pure javascript (unless I missed something).

### Actual result

When I unable the plugin, the MooTools library is added to the list of scripts loaded in the frontend. 

### Troubleshooting already performed

Under Joomla 3, in Library/Helper/Integrations.php, the function includeButtonRelocationJS calls HTMLHelper with the option 'framework' => true, which triggers the loading of MooTools.

Under Joomla 4, adding 'framework' => true has no effect in Features/ButtonInjection, function includeJ4ButtonHandler.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.9.22
* **PHP version**: 7.2.24
* **Am I using HTTPS**: Yes
* **Server Operating System**: Windows
* **My device's Operating System**: Windows 10
* **My device's Operating System version**: 20H2
* **Browser**: Any of Chrome, Firefox, Edge, Internet Explorer, Safari, Opera
* **Browser version**: all

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 5.7.14
* **Server type**: Apache
* **Server version**: 2.4.41
* **Hosting company / Local server**: local
* **Server Operating System version**: Windows 10

**Comment by nikosdion** [comment]
You are of course right. This was never meant to be set to true, it was meant to be false. I am removing the two lines as they are unnecessary.
