### ISSUE TITLE
Facebook login  varified phone

### ISSUE THREAD

**Issue by Ashishstha123** [akeeba/sociallogin#63]
Facebook login works perfectly from fb user varified by email, but fb login dont work with the user varified by phone.

**Comment by nikosdion** [comment]
Sounds about right. Facebook reports whether the account is verified. They do not consider the account verified unless it has a verified email address.

When you are trying to log in with Facebook _without_ having linked your account first or when you are trying to create a new account using your Facebook login we check to see if Facebook reports the account verified. If it is, we proceed by matching the email address reported by Facebook with Joomla's users accounts. If one is found it's logged in and linked to the Facebook account. If none is found and you've allowed user creation we create a user, activate it and link it to the Facebook account.

You can always login to Joomla first, go to your My Profile page, edit it and link your Facebook account with it, even if it is unverified. You will then be able to login by Facebook.

Do note that whether Facebook considers a Facebook account verified or not is up to Facebook, not us. We will never allow unverified Facebook accounts to log into Joomla if they have not been previously authorised for blatantly obvious security reasons. If these are not blatantly obvious to you: if I know your email and you do not have a Facebook account I can create one using your email address and my phone number. Then I could impersonate you on a site using Facebook login if SocialLogin was stupid enough to allow unverified Facebook accounts log in without being linked to the Joomla user account first.
