### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by Ashishstha123** [akeeba/sociallogin#65]
Akeeba Google integration login 
Done all setup according to documentation(https://github.com/akeeba/sociallogin/wiki/Google).

Set up both http and https Authorized redirect URIs
https://www.yohobazaar.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw
http://www.yohobazaar.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw

But following error occurs
Authorization Error
Error 400: redirect_uri_mismatch

![Screenshot (117)](https://user-images.githubusercontent.com/30790681/101156480-c5dfe380-3650-11eb-90e6-bae6a05c2ede.png)

**Comment by nikosdion** [comment]
I cannot reproduce this issue with an app set up on Google according to the documentation Wiki.

Please make sure that your redirect URI is set to `https://yohobazaar.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw` i.e. exactly as it is printed in the error message you received from Google (which is what the Wiki tells you to do anyway).

You can do that from https://console.developers.google.com/projectselector/apis/library, select your site project, hamburger menu top left, API & Services, Credentials, click your credentials name, see the Authorized Redirect URIs area.

**Comment by nikosdion** [comment]
In case you still can't spot the problem, let me make it very clear to you. Open the documentation wiki. Look at the "Useful information about the Valid OAuth redirect URIs" header. Read the second bullet point. It is addressing your problem.

The redirect URI you entered is `https://www.yohobazaar.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw` (_with_ www)

You are accessing your site through the yohobazaar.com domain (**WITHOUT** www)

The redirect URI in this case is `https://yohobazaar.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw` (**WITHOUT** www)

Therefore you ALSO need to add the redirect URI **WITHOUT** www in Google.
