### ISSUE TITLE
I cannot add domain name

### ISSUE THREAD

**Issue by uzbaby** [akeeba/sociallogin#66]
I made all necessary thing with App development. 
Add my domain as: uzbaby.uz and uzbaby.uz/forum

But then I see this:

Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

**Comment by nikosdion** [comment]
This message comes from Facebook itself and has to do with your configuration of your Facebook application on the Facebook Developer site. As a result it's not an issue with our software.

**Comment by uzbaby** [comment]
So does it mean it will not work? I thought maybe I made something wrong with adding domain name as was shown in documentations.

**Comment by nikosdion** [comment]
It will work if you follow the documentation. See https://www.dionysopoulos.me my personal site where I'm using Facebook login.

Remember that http://www.uzbaby.uz, https://www.uzbaby.uz, http://uzbaby.uz and https://uzbaby.uz are four different sites to Facebook. Check your settings again.
