### ISSUE TITLE
 language file and redirection

### ISSUE THREAD

**Issue by macaucentral** [akeeba/sociallogin#69]
Hi

I have below requests:

plugin language file to translate all the error message to users

after social login, user always redirected to the user profile page. add setting to disable such redirection, and keep user login on the page they are seeing.

**Comment by nikosdion** [comment]
It's already possible to translate error messages for each plugin.

Social Login redirects back to the page it was called from. You can override the redirection location by integrating it with template overrides per the documentation.

As a result your issue is closed as invalid.
