### ISSUE TITLE
[OTHER] redirection setup

### ISSUE THREAD

**Issue by skyfranky** [akeeba/sociallogin#70]
Hi

I setup below url in FB and Google setting. After socail login FB, I am redirected to my website homepage. After Gmail login, I am redirected to user profile page. Both not redirect back to the page I did the login. May I know what setting I am missing?

https://www.example.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw
http://www.example.com/index.php?option=com_ajax&group=sociallogin&plugin=facebook&format=raw

**Comment by nikosdion** [comment]
The plugin you use for authentication is irrelevant. The redirection is handled by the system plugin. 

The way it works is this.

The current page's URL is saved in the user session by the code in the System – Social Login plugin whenever the login buttons are displayed.

Each authentication plugin creates a URL for its button which redirects you to the remote service for authentication. 

The service comes back to a temporary URL handled using com_ajax. 

When the returned data is validated against the remote service, the backend code of the System – Social Login plugin performs a redirect to the URL stored in the user session.

If you have displayed multiple pages on your site e.g. in different tabs in the same browser session then the LAST page to load defines the redirection. Do not load multiple pages in many tabs, only to go back to an older tab to log in. Your redirection will not work correctly.

If you are loading multiple login buttons in different areas of your site, one of them using the custom integration with template overrides, only the last one to be rendered by Joomla defines the redirection. Beware! Joomla does NOT render components, plugins and modules in the same order they display on the page. Components are rendered first. Modules are rendered second, when the site's template is being parsed. Buttons created through the system plugin are the last thing to happen. Try to only display one login area. If that's not possible remember that this may cause redirection issues on your site.

You can see that all redirections work correctly on my own blog, www.dionysopoulos.me. Both the right hand sidebar login buttons and the login buttons in each article's comment section take you to the same page you were before. However, if you have a tab on the home page, open an article in the background and try to use social login in the front-page tab you will end up in the article page, not the front-end. This is normal and expected. That's how things are supposed to work.

There is no other way to do it. Authentication services for social media / big tech does not typically support a redirection URL. You'd have to end up in the same page every single time which is user hostile. Having the social login redirect to the last visited page makes sense. That's how everyone else is implementing social login.

**Comment by skyfranky** [comment]
thank you for the detail explanation, it helps a lot and should be part of the document. 

I have a few different login page from popup login module to extension builtin login feature with template override to insert social buttons. and I think this is causing the redirection issue.

from an extension popup page social login, I even got this page for redirection. If I clicked back, I am already login.
https://monosnap.com/file/lnOlb0RPJ34Oiw4y2W6FKaiXp2C3FX

**Comment by nikosdion** [comment]
I updated the [Overview documentation page](https://github.com/akeeba/sociallogin/wiki/Overview-of-the-Social-Login-system) to include this information.

Regarding your popup page, since it's a _page_ on your site (as opposed to an inline modal dialog inside another page of your site) it is indeed the last page loaded. Therefore this is indeed the redirection target. If possible use a custom integration with template overrides for that page so you can set up a more sensible redirection target URL.

I will mark this issue as a question and close it since it's exactly how the plugins are supposed to work due to external limitations.
