### ISSUE TITLE
[OTHER] sociallogin Linkedin : not import...

### ISSUE THREAD

**Issue by Puby14** [akeeba/sociallogin#71]
Dear All
I try to use sociallogin for linkedin connect. ( Joomla 3.9.25., php 7.4.12 )  The contact is created but only email-adresse is imported.
I am not a big coder - what to do ?

**Comment by nikosdion** [comment]
SocialLogin will only create a user account, not a contact. I will assume you are talking about the Joomla! user record. If you are actually talking about a contact that's not something related to SocialLogin and you need to check the options in Joomla's own Contacts extension and its “User - Contact Creator” plugin.

Regarding the user. We ask LinkedIn to return us the user's name and email address. If you didn't give your LinkedIn application the `r_liteprofile` scope per [our documentation](https://github.com/akeeba/sociallogin/wiki/LinkedIn) the full name will NOT be returned from LinkedIn to your site. As a result SocialLogin will use the fake name "John Doe". 

Also note that if LInkedIn didn't approve your use of the `r_liteprofile` scope you will also have the same problem. This is beyond the scope of what we can reasonably help with and you'd need to ask LinkedIn why they denied your application the use of this privilege.

**Comment by nikosdion** [comment]
This issue has been addressed in a new version published yesterday. There was an inverted logic consuming the profile information, allowing the email to go through but not the actual full name. This has now been fixed.
