### ISSUE TITLE
Joomla users are being created with name "John Doe" and username john.doe, when signing in with LinkedIn

### ISSUE THREAD

**Issue by regexaurus** [akeeba/sociallogin#75]
LinkedIn users that have entered a name in their public profile (not "John Doe"!) are having Joomla accounts created with the name "John Doe" and the username john.doe, when clicking the Sign in with LinkedIn button. It seems the LinkedIn integration plugin has a problem with retrieving the name from the LinkedIn profile? See this Joomla forum topic: https://forum.joomla.org/viewtopic.php?f=715&t=986521

https://github.com/akeeba/sociallogin/blob/807b53b09f8a0fa122c8562b6a72bbf01e1010a9/plugins/sociallogin/linkedin/linkedin.php#L153

**Comment by regexaurus** [comment]
OAuth scopes included/allowed in my LinkedIn app:

![LinkedInOauthScopes](https://user-images.githubusercontent.com/5941462/119276497-8bf79f00-bbe8-11eb-9a56-bb40ab1834dc.png)

**Comment by nikosdion** [comment]
Thank you for your report! This issue is now fixed with commit https://github.com/akeeba/sociallogin/commit/ea9d7a1a2fa10d8fc6efcdd599b55f65f06f3224 A new version will be released later today or tomorrow as planned.
