### ISSUE TITLE
Valid OAuth Redirect URIs - what do I wrong

### ISSUE THREAD

**Issue by BGBlab** [akeeba/sociallogin#77]
Hello
I have a joomla app and I am not able to configure "Valid OAuth Redirect URIs" in Facebook for developers.
The Facebook login button is on page  https://estryszek.pl/pl/login-form
![image](https://user-images.githubusercontent.com/61151308/127054857-eeeeac3d-9599-4d22-99a6-fb666db0292a.png)

And the error I can see after clicking the button is:
![image](https://user-images.githubusercontent.com/61151308/127055193-c07f5794-bb08-46fd-9633-720bb9ad1c8f.png)

https://www.facebook.com/dialog/oauth?response_type=code&client_id=1601795433497606&redirect_uri=https%3A%2F%2Festryszek.pl%2Findex.php%3Foption%3Dcom_ajax%26group%3Dsociallogin%26plugin%3Dfacebook%26format%3Draw&scope=public_profile%2Cemail

I tried with many different URIs with no success.
What I should put there to make it working?

**Comment by nikosdion** [comment]
Please follow the [Setup instructions](https://github.com/akeeba/sociallogin/wiki/Facebook#setup-on-facebook). As you can see, you need to setup both the App domains (in your case `estryszek.pl` and `www.estryszek.pl`) and the Vaid OAuth Redirect URIs (in your case `https://estryszek.pl/index.php?option=com_ajax&group=sociallogin&plugin=facebook&format=raw` and `https://www.estryszek.pl/index.php?option=com_ajax&group=sociallogin&plugin=facebook&format=raw`).

Both App domains _and_ Valid OAuth Redirect URIs must be set in Facebook. The App domains must also match the domains used in the Valid OAuth Redirect URIs. This is a double security check made by Facebook to ensure that no third party sites can spoof the Facebook login of your site, preventing entire classes of attacks against your users.

**Comment by BGBlab** [comment]
"The App domains must also match the domains used in the Valid OAuth Redirect URIs" - This is a part that made my mistake.
Thank you so much!!!!

**Comment by nikosdion** [comment]
You're welcome!
