### ISSUE TITLE
Login with Yahoo

### ISSUE THREAD

**Issue by nikosdion** [akeeba/sociallogin#8]
Note: maybe wait until Yahoo gets fully rebranded

[Yahoo! OAuth API](https://developer.yahoo.com/oauth2/guide/flows_authcode/)
[Yahoo! OAuth OpenID API](https://developer.yahoo.com/oauth2/guide/openid_connect/getting_started.html)

We need to use the `openid sdps-r` scopes (use OpenID and read-only access to user Profiles). When the server replies with an access token it will also include `id_token` which [needs to be decoded](https://developer.yahoo.com/oauth2/guide/openid_connect/decode_id_token.html). The token's payload includes the email address of the user.

**Comment by mfino** [comment]
Is there a way to make akeeba social login work with Yahoo accounts yet?

**Comment by nikosdion** [comment]
Look at the top of the issue's page on GitHub. If it reads "open" it means it's work not completed, i.e. the feature is not implemented yet. If the work is completed you will see that the issue is closed and there is a commit referenced with the code that implements it. This applies to all issues here.
