### ISSUE TITLE
[DOCS] Invalid namespace and function call

### ISSUE THREAD

**Issue by sakiss** [akeeba/sociallogin#80]
### Documentation page affected

https://github.com/akeeba/sociallogin/wiki/Integrating-with-template-overrides

### Your concern
The used namespace and function do not seem to exist.

### Old documentation passage

`\Akeeba\SocialLogin\Library\Helper\Integrations`

### Write the new documentation passage.
`\Joomla\Plugin\System\SocialLogin\Library\Helper\Integrations`

`getSocialLoginButtons()` does not exist. Is there a replacement for that?

Version 4.0.0 downloaded from akeeba.com

**Comment by nikosdion** [comment]
I have not updated the documentation for Joomla 4 yet. Right now there is no time. Sorry.

**Comment by nikosdion** [comment]
I actually fixed that a month ago but forgot to post here. Sorry! The doc page now has separate J3 and J4 sections.
