### ISSUE TITLE
New User Email Using Language ini Instead of Mail Template

### ISSUE THREAD

**Issue by kevinsguides** [akeeba/sociallogin#81]
### Steps to reproduce the issue
Create a new account via social login

### Expected result
The mail template for new user account is used to send the email, perhaps Users: New account without activation

### Actual result
The language from COM_USERS_EMAIL_ACCOUNT_DETAILS and COM_USERS_EMAIL_REGISTERED_BODY_NOPW is sent , {NAME} and {SITENAME} are not replaced with the appropriate user information in the default email, I'm assuming because Joomla 4 wants us to use the mail templates.

### Troubleshooting already performed
Looked through readmes, and wiki to see if there was anything on this, didn't find anything. Checked language options to see if I was missing something on {VARIABLE} display but didn't find anything.

#### Mandatory information
Latest version of social plugins 4.0
Joomla! 4.0.3
PHP 7.4.22
HTTPS
Any Browser/OS

### Additional comments
I just created a language override and removed all variables from the message as a workaround, which is fine for me, but others may want more customized messages sent after account activation.

**Comment by nikosdion** [comment]
Thank you! The integration with the email was written before Joomla 4 started using the mail templates. I have now changed SocialLogin to go through com_users' model to perform the user registration, solving this issue and making sure it will not happen again.
