### ISSUE TITLE
Nothing happens when we click on GH button.

### ISSUE THREAD

**Issue by N6REJ** [akeeba/sociallogin#84]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue
we click on the github buttton and the favicon blinks but that is all

### Expected result

either github login info request is show or an error saying its the wrong username/password

### Actual result

nothing but a favicon flash

### Troubleshooting already performed

double checked url and codes.
turned maximum error reporting on and got
```
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/bearsampp/public_html/components/com_users/tmpl/login/default_login.php on line 33

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/bearsampp/public_html/components/com_users/tmpl/login/default_login.php on line 45
```

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.1.5
* **PHP version**:  8.1.8
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows
* **My device's Operating System version**:  win 10 x64 pro
* **Browser**: Chrome
* **Browser version**:  Version 104.0.5112.81 (Official Build) (64-bit)

#### Good to have information

* **MySQL version**: 10.3.35-MariaDB-cll-lve
* **Server type**: Apache,
* **Server version**: unknown
* **Hosting company  abivia.net
* **Server Operating System version**:  Linux ssc010.abivia.net 3.10.0-962.3.2.lve1.5.42.el7.x86_64 #1 SMP Mon Nov 9 08:11:18 EST 2020 x86_64

**Comment by nikosdion** [comment]
Cannot reproduce. For proof that this feature works go to https://www.dionysopoulos.me and create an account (or log in) using GitHub. It works fine.

Also note that the deprecated notices that you posted are notices, not errors, and they come from Joomla, not our code.

Your issue sounds like a JavaScript issue to me. Since the JS we include with our software does work on both development and a real world site whatever problem you have is caused either by your site's configuration or some third party software. Either way, it's not a bug and there is nothing for me to change in this software.

**Comment by N6REJ** [comment]
*sigH* not my night

**Comment by nikosdion** [comment]
Sorry, man :( You seem to be on a bad luck streak (inferring from your attempts to test the PR at the Joomla GitHub repo).

**Comment by N6REJ** [comment]
and I just completely broke my http://github.com/Bearsampp/Bearsampp project and have no clue where/why nor how.
We released a perfectly working copy on tuesday and tonight I try to do a build and its trashed.  Which tbh is extremely depressing cause I don't know how to roll back to what worked.
I'm not a git guru.  The pr issue was just icing on the cake.

**Comment by N6REJ** [comment]
since it fails on admin page it would have to be some extension wouldn't it?

**Comment by nikosdion** [comment]
You can figure out what changes you made from tagging a release to your current branch like this.

On your local working copy check out the branch you are developing on.

On the command line do `git diff TagName..HEAD` where TagName is the name of your tag, e.g. `v.1.2.3`. The diff will help you identify your changes and hopefully find your problem.

The diff command works between commits as well. The syntax of the stuff to the right of diff is OldCommit..NewCommit (note the two dots). Both OldCommit and NewCommit can be a commit hash, a tag name, a HEAD expression (HEAD for latest commit, HEAD~1 for the previous commit, HEAD~2 for two commits ago...) or something in the form of remote/something where remote is the name of a remote you have specified (do git remote -v to list them) and something is a commit has, tag name or HEAD expression. Believe me, this does get used A LOT when I am developing.

**Comment by N6REJ** [comment]
alright.. ty... This is my first major dev  project, especially Joomla related, and its a huge set of repos.
i'm grateful its only 3 days work lost not the  year and a half I spent getting this far.
idk if you know what neard is/was but we're modernizing it.

**Comment by nikosdion** [comment]
As long as you are using Git you will never lose anything more than the work between the last commit and a few seconds ago when you realised something's not right. Therefore committing early and often minimises how much you will lose.

That was the primary reason I started using Git around 2010-ish. Before that I was using Subversion which a. required an Internet connection to the centralised server to commit and b. was notorious for screwing up big time when merging branches. Between these two traits and the fact that at the time I was mostly working off-line (as I was often to be found at my under construction house with a 3G mobile cap of 200Mb per month and a cost of 10 Euros per 100 Mb beyond that) I was suffering with Subversion. In despair I tried Git one day and never looked back. Git has gotten out of some VERY tough spots.

**Comment by N6REJ** [comment]
I appreciate the encouragement.  I'm sure its my bi-polar acting up but this minute I'm devastated

**Comment by nikosdion** [comment]
As someone with ADHD I can very much relate. Small problems can throw me into an emotional tailspin. Meds help but they are not a panacea. Take a deep breath, cheer yourself up on the knowledge that all is NOT lost, take a good night's sleep and tomorrow you'll figure it out.

Life pro tip: according to relatively recent neuroscience research, we have a finite amount of mental energy which helps our conscious self cope with emotional, physical and mental hardship. When we expend too much energy on one kind of these tasks we are far more likely to give up quicker on the other tasks in these categories. Surprisingly, this is mostly regulated by _glucose_. When you wake up and about 10' before sitting down to attack your problem eat a bit of something sweet, e.g. a couple squares of chocolate. You'll find the task much more doable.

**Comment by N6REJ** [comment]
@nikosdion I found this when debug is on maximum

```
ttp://bearsampp.com/index.php?option=com_ajax&group=sociallogin&plugin=github&format=raw&error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch
```

Notice the missing "h" in "http://"

**Comment by nikosdion** [comment]
You have entered the Authorization callback URL wrong in your GitHub OAuth App. See https://github.com/akeeba/sociallogin/wiki/GitHub

> In the Authorization callback URL field use http://www.example.com/index.php?option=com_ajax&group=sociallogin&plugin=github&format=raw where http://www.example.com MUST be replaced with your site's URL. For example, if your site is accessible at http://www.abrandnewsite.com/mysite then the Callback URL field must be http://www.abrandnewsite.com/mysite/index.php?option=com_ajax&group=sociallogin&plugin=github&format=raw.

You forgot the `h` in front of `http://`.

**Comment by N6REJ** [comment]
what a silly mistake... ty nic!
