### ISSUE TITLE
Warning Could not create a new user on our site: Form::loadForm could not load file

### ISSUE THREAD

**Issue by Pakeydev** [akeeba/sociallogin#87]
### Steps to reproduce the issue

Login or register using 'Sign in with Google' button. 

Got this error when new user try to login/register;

`Could not create a new user on our site: Form::loadForm could not load file`

### Expected result

Expecting user to register successfully.

### Actual result

No user registered on the site.

### Troubleshooting already performed

I don't know how to troubleshooting this.

### System information

Joomla! version: Joomla! 4.2.3 Stable
PHP version: 8.1.10
Am I using HTTPS: Yes
Server Operating System: Linux
My device's Operating System: Windows
My device's Operating System version: Windows 10
Browser: Chrome
Browser version: Version 106.0.5249.91

**Comment by nikosdion** [comment]
I just released version 4.2.0 which addresses this issue.
