### ISSUE TITLE
Login with LinkedIn

### ISSUE THREAD

**Issue by nikosdion** [akeeba/sociallogin#9]
Integrate [LinkedIn OAuth API](https://developer.linkedin.com/docs/signin-with-linkedin)

**Comment by nikosdion** [comment]
This plugin is removed in SocialLogin 3.0.1. The v2 APIs, made mandatory for all LInkedIn Apps created after December 2018, do not return the email address of the user. As a result we can no longer log in users who have not yet linked their Joomla profile with their LinkedIn account and we can no longer create new user accounts. This makes the integration useless since it cannot provide what we consider the minimum common level of features for integration plugins.

**Comment by cheyennemtnman** [comment]
Need to update Akeeba Site Documentation... I downloaded based on the site saying LinkedIn was available. I was surprised not to see it available in the Plugins.

**Comment by nikosdion** [comment]
The plugin is there but it’s not being installed. I am planning on releasing a new version by Tuesday to address this and another issue. 

Nicholas K. Dionysopoulos Director


Akeeba Ltd • 51 Metochiou Str. • Flat 303 • 1101 Nicosia • Cyprus 

Web administrator and security tools you can trust.
