### ISSUE TITLE
اسامة حسين 

### ISSUE THREAD

**Issue by 771270678** [akeeba/sociallogin#90]
We kindly request that you contact us about for-a-fee personalised support and custom development services through our site's contact page:

https://www.akeeba.com/contact-us.html

While you can do that through a GitHub issue be advised that you will be asked to give us your email address for further contact in a public conversation resource.

**Comment by nikosdion** [comment]
Hello,

If you want to contact us about for-a-fee personalised support and/or custom development please go to https://www.akeeba.com/contact-us.html and submit a new contact form with type “Pre-sales request”.

When you submit a GitHub issue we do not have your email address or any other way for communicating with you in private.

Thank you!

**Comment by 771270678** [comment]
@771270678
