### ISSUE TITLE
Unable to log in with Twitter

### ISSUE THREAD

**Issue by raulprietofdez** [akeeba/sociallogin#93]
### Steps to reproduce the issue

Visit https://www.raulprietofernandez.net/blog and Click on "Login con Twitter"

### Expected result

Login with Twitter account

### Actual result

If we login using Twitter, a error message is displayed and we're redirected to the / (website root)

Error message is displayed:
![image](https://user-images.githubusercontent.com/55446986/212546260-eb10a98d-aea9-42fa-ba15-8cae58eaa04e.png)

Plugin config:
![image](https://user-images.githubusercontent.com/55446986/212546353-5dc534f5-cd8c-42aa-a2d4-19b2d897643c.png)

### Troubleshooting already performed

- Removed the module and created again.
- Created a new APP Oauth in Twitter with different credentials.
- Checked with Chrome, Firefox and from Android 12 with Chrome.
- Enabled debug in Joomla but no error are printed.

#### Mandatory information

* **Joomla! version**: 3.10.11
* **PHP version**: 8.0.27
* **Am I using HTTPS**: Yes
* **Server Operating System**:  Linux
* **My device's Operating System**: Windows and Android...
* **My device's Operating System version**: e.g. Windows 10, Android 12
* **Browser**: Chrome and Firefox
* **Browser version**: 108.0.5359.126 

### Additional comments
I think there is something different ion Linkedin side....

**Comment by nikosdion** [comment]
It looks like Twitter removed the ability to have a callback URL for logging into a website, forcing you to use their JavaScript-based login method instead. Unfortunately, the whole point of having SocialLogin is to NOT use the privacy-invading JavaScript provided by social media networks.

As a result, I am going to remove the Twitter login from SocialLogin.

**Comment by raulprietofdez** [comment]
Hello Nikosdion:

I migrated from a different 3rd party plugin to your Social Akeeba Login and Twitter failed with the other 3rd party plugin too. It's a pity!

Regards and thanks for your help.

**Comment by nikosdion** [comment]
Yeah, it's a Twitter issue, not something any of us developers can fix on our end. 

To give you an idea how stupid Twitter has gotten, the change is not documented anywhere. Moreover, they are throwing an error message in a completely different way than they have documented they should be throwing error messages — and in violation of the OAuth specification they allegedly implement. It's like an intern was told to "disable the f…ing thing YESTERDAY!" and haphazardly added a quick `die` statement in the code to appease the ~mentally unstable overlord with a god complex and a penchant of human sacrifice~ rather volatile new management.

On the plus side, nobody expects Twitter to last the year. I can't say I'll miss it.
